### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by johnnyshields** [tablecheck/mongoid-ultra#13]
- [ ] Establish maintainers and governance board.
- [ ] Publish documentation.
- [x] Drop support for old Ruby, Rails, and MongoDB server versions.
- [x] Full documentation coverage.
- [ ] Full Rubocop compliance and coverage.
- [ ] Remove all monkey-patching.
- [ ] Merge patches rejected by MongoDB.
- [ ] Improve major performance benchmarks by 30%+ over MongoDB Mongoid.
- [ ] Refactor persistence type-validation (mongoize, etc.)
- [ ] Extract unsafe chaining `and` and `or` operators to a gem. Require usage of `all_of` and `any_of` instead.
- [ ] Extract `:field.in => [1, 2, 3]` query syntax to a gem. Require usage of `field: { '$in' => [1, 2, 3] }` instead.
- [ ] Allow symbol instead of classes in `field :type` declarations.
- [ ] Refactor relations (`belongs_to_one`, `belongs_to_many`)
